/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hackathon;
import org.eclipse.paho.client.mqttv3.*;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;
public class App {
    /*MqttClient mqttClient = new MqttClient("ssl://mr-connection-rzp5w502h9r.messaging.solace.cloud:8883", "HelloWorldSub");
    MqttConnectOptions connectionOptions = new MqttConnectOptions();
    connectionOptions.setUsername("solace-cloud-client");
    connectionOptions.setPassword("berj6d3d4kfrjs8q64llc8ntae".toCharArray());
    mqttClient.connect(connectionOptions);*/


    public static void main(String[] args) throws MqttException {
        String broker = "ssl://mr-connection-rzp5w502h9r.messaging.solace.cloud:8883";
        String clientId = "HelloWorldSub";

        MqttClient mqttClient = new MqttClient(broker, clientId, new MemoryPersistence());

        MqttConnectOptions connectionOptions = new MqttConnectOptions();
        connectionOptions.setUserName("solace-cloud-client");
        connectionOptions.setPassword("berj6d3d4kfrjs8q64llc8ntae".toCharArray());
        connectionOptions.setCleanSession(true);

        // Enable SSL/TLS
       // connectionOptions.setSocketFactory(SslUtil.getSocketFactory());

        mqttClient.connect(connectionOptions);

        // Your code for subscribing or publishing goes here

        // Disconnect when done
        mqttClient.disconnect();
        mqttClient.close();
    }



}
